#ifndef MATRIX_API_MACRO_HEADER
#define MATRIX_API_MACRO_HEADER
#endif // MATRIX_API_MACRO_HEADER

#define MATRIX_SIZE_NOT_EQUAL -1001
#define MATRIX_ROW_NOT_EQUAL -1002
#define MATRIX_COLUMN_NOT_EQUAL -1003
#define MATRIX_ROW_TOO_LARGE -1004
#define MATRIX_COL_TOO_LARGE -1005


